#!/usr/bin/env bash

set -euf -o pipefail

day=${1:-$(date +%-d)}
year=${2:-$(date +%Y)}

aocf checkout $day $year

cargo init "day-$day"
sed -i "s/\(\"day-[0-9]*\"\)\$/\1,\n  \"day-$day\"/" Cargo.toml
sed -i '1s/^/const INPUT: \&str = include_str!("input");\n\n/' day-$day/src/main.rs
aocf input > day-$day/src/input
aocf brief > day-$day/brief.md

git add Cargo.toml
git add day-$day

lvim day-$day/brief.md
